services:
  backend-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
      - redis
    environment:
      # - MONGO_URL=mongodb://mongo-db:27017/dataSyncTask
      - MONGO_URL=mongodb+srv://shivanishwaira_db_user:PlC7rwCAyEJr2E8Q@cluster0.thp84z1.mongodb.net/dataSyncTask?appName=Cluster0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # volumes:
    #   - .:/app
    volumes:
     - .:/app
     - /app/node_modules

    command: ["npm", "run", "start"]  # or node app.js

  worker-app:
    build: .
    depends_on:
      - mongo-db
      - redis
    environment:
      # - MONGO_URL=mongodb://mongo-db:27017/dataSyncTask
      - MONGO_URL=mongodb+srv://shivanishwaira_db_user:PlC7rwCAyEJr2E8Q@cluster0.thp84z1.mongodb.net/dataSyncTask?appName=Cluster0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # volumes:
    #   - .:/app

    volumes:
     - .:/app
     - /app/node_modules

    command: ["node", "./Jobs/workers/reminderWorker.js"]

  mongo-db:
    image: mongo:6
    # ports:
    # - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
